version: '3.4'
services:
  chrome:
    image: selenium/node-chrome:4.21.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - automation_network

  firefox:
    image: selenium/node-firefox:4.21.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - automation_network

#  chrome_video:
#    image: selenium/video:ffmpeg-6.1.1-20240522
#    volumes:
#      - /tmp/videos:/videos
#    depends_on:
#      - chrome
#    environment:
#      - DISPLAY_CONTAINER_NAME=chrome
#      - FILE_NAME=chrome_video.mp4
#    networks:
#      - automation_network
#
#  firefox_video:
#    image: selenium/video:ffmpeg-6.1.1-20240522
#    volumes:
#      - /tmp/videos:/videos
#    depends_on:
#      - firefox
#    environment:
#      - DISPLAY_CONTAINER_NAME=firefox
#      - FILE_NAME=firefox_video.mp4
#    networks:
#      - automation_network

  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - automation_network

  # Uncomment the below code block, if you want
  # to run tests using Dynamic Selenium Grid

  # node-docker:
  #   image: selenium/node-docker:4.21.0
  #   volumes:
  #     - ./assets:/opt/selenium/assets
  #     - ./GridConfig/config.toml:/opt/bin/config.toml
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   networks:
  #     - automation_network

  # selenium-hub:
  #   image: selenium/hub:4.21.0
  #   container_name: selenium-hub
  #   ports:
  #     - "4442:4442"
  #     - "4443:4443"
  #     - "4444:4444"
  #   networks:
  #     - automation_network

networks:
  automation_network: